### ISSUE TITLE
Calling `importlib_resources.files` with an editable install fails

### ISSUE THREAD

**Issue by GarrStau** [python/importlib_resources#311] opened 2024-06-29 03:17 UTC
When calling `importlib_resources.files("sample-namespace")` to retrieve a text file, an exception is thrown if an editable install has been done for the package.

I am able to trigger this with a relatively simple setup - I have a namespace package with two files, `sample.txt` and a `__main__.py` that has two lines:
`from importlib_resources import files`
`files("sample-namespace")`

In a venv with only importlib_resources 6.4.0 installed, calling "py -m sample-namespace" works without issue if `sample-namespace` is not installed or normally installed, but will fail if it is installed in editable mode.

The error is thrown in the MultiplexedPath constructor, because `'__editable__.sample_namespace-1.0.finder.__path_hook__'` is one of the paths provided, and `path.is_dir()` is False leading to raising NotADirectoryError.

I'm not convinced that I'm doing everything right, but I don't know of any limitations with editable installs. I'm not very familiar with this library, but if there's anything I can do to help, let me know.

Thank you!

```
(.venv) PS C:\git\TEST\test-importlib-resources-files-editable> py -m sample-namespace
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\git\TEST\test-importlib-resources-files-editable\sample-namespace\__main__.py", line 3, in <module>
    files("sample-namespace")
  File "C:\git\TEST\test-importlib-resources-files-editable\.venv\Lib\site-packages\importlib_resources\_common.py", line 46, in wrapper
    return func(anchor)
           ^^^^^^^^^^^^
  File "C:\git\TEST\test-importlib-resources-files-editable\.venv\Lib\site-packages\importlib_resources\_common.py", line 56, in files
    return from_package(resolve(anchor))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\TEST\test-importlib-resources-files-editable\.venv\Lib\site-packages\importlib_resources\_common.py", line 116, in from_package
    reader = spec.loader.get_resource_reader(spec.name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\TEST\test-importlib-resources-files-editable\.venv\Lib\site-packages\importlib_resources\future\adapters.py", line 66, in get_resource_reader
    or super().get_resource_reader(name)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\TEST\test-importlib-resources-files-editable\.venv\Lib\site-packages\importlib_resources\_adapters.py", line 29, in get_resource_reader
    return CompatibilityFiles(self.spec)._native()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\TEST\test-importlib-resources-files-editable\.venv\Lib\site-packages\importlib_resources\_adapters.py", line 153, in _native
    reader = self._reader
             ^^^^^^^^^^^^
  File "C:\git\TEST\test-importlib-resources-files-editable\.venv\Lib\site-packages\importlib_resources\_adapters.py", line 147, in _reader
    return self.spec.loader.get_resource_reader(self.spec.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1425, in get_resource_reader
  File "C:\Users\garrstau\AppData\Local\Programs\Python\Python312\Lib\importlib\resources\readers.py", line 133, in __init__
    self.path = MultiplexedPath(*list(namespace_path))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\garrstau\AppData\Local\Programs\Python\Python312\Lib\importlib\resources\readers.py", line 70, in __init__
    raise NotADirectoryError('MultiplexedPath only supports directories')
NotADirectoryError: MultiplexedPath only supports directories
```

**Comment by jaraco** [comment] 2024-08-19 23:11
I recently encountered this error too in [jaraco.imaging](https://github.com/jaraco/jaraco.imaging/actions/runs/9618805253). The same code previously passed on Apr 24, so my guess is there was some regression since then.

**Comment by jaraco** [comment] 2024-08-19 23:34
For what it's worth, editable installs used to work, but not since the path hook was added to the namespace path (probably a newer form of editable install).

Here's what I'm seeing for namespace path:

```
> /opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/resources/readers.py(133)__init__()
-> self.path = MultiplexedPath(*list(namespace_path))
(Pdb) namespace_path
_NamespacePath(['/Users/jaraco/code/jaraco/jaraco.imaging/.tox/py/lib/python3.12/site-packages/jaraco', '/Users/jaraco/code/jaraco/jaraco.imaging/jaraco', '__editable__.jaraco.imaging-2.1.1.dev173+gbde5bcf.finder.__path_hook__'])
(Pdb) import jaraco
(Pdb) jaraco.__path__
_NamespacePath(['/Users/jaraco/code/jaraco/jaraco.imaging/.tox/py/lib/python3.12/site-packages/jaraco', '/Users/jaraco/code/jaraco/jaraco.imaging/jaraco', '__editable__.jaraco.imaging-2.1.1.dev173+gbde5bcf.finder.__path_hook__'])
```

@abravalheri Do you know what it is that's adding that `__editable__` entry to the `_NamespacePath`? Is there a spec that allows that path to be something other than an importable path? What should `importlib_resources` be doing (if anything) to honor that path entry?

**Comment by jaraco** [comment] 2024-08-20 00:11
Oh, I see https://github.com/pypa/setuptools/issues/3548 is already tracking the issue.

**Comment by abravalheri** [comment] 2024-08-20 07:09
> Do you know what it is that's adding that __editable__ entry to the _NamespacePath? Is there a spec that allows that path to be something other than an importable path?

This is added by a `.pth` file added on purpose by the `editable_wheel` command in setuptools to the editable wheel. The objective is to trigger a [`PathEntryFinder`](https://docs.python.org/3/reference/import.html#path-entry-finders), which is so far the only known way in the community to implement namespace packages via import finders. The entry added to `sys.path` is a path item... but not a conventional one: it is a path that does not exist but is there only to force the `PathEntryFinder` to be called.

I believe that the standard that supports this is PEP 302. In the text of the PEP it is suggested that adding a "non existing" path is an acceptable approach for a different class of problems (but nonetheless the approach described still adds a non existing file to `sys.path`):

> For now, if a hook is required after sys.path has been processed, it can be simulated by adding an arbitrary “cookie” string at the end of sys.path, and having the required hook associated with this cookie, via the normal sys.path_hooks processing. In the longer term, the path handling code will become a “real” hook on sys.meta_path, and at that stage it will be possible to insert user-defined hooks either before or after it.

The [Python docs](https://docs.python.org/3/reference/import.html#path-entry-finders) also explicitly say:

> sys.path contains a list of strings providing search locations for modules and packages. It is initialized from the PYTHONPATH environment variable and various other installation- and implementation-specific defaults. Entries in sys.path can name directories on the file system, zip files, and potentially other “locations” (see the site module) that should be searched for modules, such as URLs, or database queries. Only strings should be present on sys.path; all other data types are ignored.

Also here in https://docs.python.org/3/reference/import.html#finders-and-loaders:

> The import path is a list of locations that may name file system paths or zip files. It can also be extended to search for any locatable resource, such as those identified by URLs.

So my interpretation is that `sys.path` can contain all sorts of stuff that are searched by finders/loaders. The text even mentions database queries, which is a pretty good example of not a regular file path. Nevertheless, since there is an associated `PathEntryFinder`, these entries work effectively as an "importable path" but not in the conventional sense.

> What should importlib_resources be doing (if anything) to honor that path entry?

I am not sure here. PEP 320 mentions `loader.get_data(path)`. I did not implement any custom loader in `setuptools`, just the finders that rely on standard functions of importlib, so all the loaders produced should also be fairly standard. Maybe the standard loaders of importlib implement the `get_data` protocol?

Another thought is that sometimes editable namespace packages do not correspond to an actual directory in disk and it is only simulated by the importlib machinery. For example, consider that a developer use `package_dir` in setuptools to remap the file paths and point package `a.b` to a project folder called `x`. We can map `a.b` to `x`, but there is no correspondence for `a`.

In that case, users are better off if they avoid calling `importlib_resources.files("a")`. Instead, they will have to be more specific and call `importlib_resources.files("a.b")`.

---

I believe that pypa/setuptools#3548 regards a different original problem.

To be honest, since we never got a reproducer, I believe that the original problem might be cause by another piece of software that expects all entries of `sys.path` to be existing regular paths to files or directories (and as explained above that is not how it is described by the Python docs). And if that is the case there is not much to be done by setuptools itself.

**Comment by abravalheri** [comment] 2024-08-20 08:33
> but I don't know of any limitations with editable installs.

@GarrStau , there is a non-exhaustive list in https://setuptools.pypa.io/en/latest/userguide/development_mode.html#limitations.

**Comment by jaraco** [comment] 2024-08-20 15:34
That helps a lot. Thanks for the context. I do believe it makes sense for importlib resources to support this mode.

**Comment by jaraco** [comment] 2024-08-20 16:03
I do see that `importlib_resources.future.adapters.TraversableResourcesLoader.get_resource_reader` is getting to `super().get_resource_reader(name)`, so `._standard_reader()` would have to have been called before that, so it's probably just the case that `_namespace_reader` is not resolving because of this reported issue. That is, there's probably a `ValueError` on line 149:

https://github.com/python/importlib_resources/blob/d02141768b62468e46064614276036ea5c746056/importlib_resources/readers.py#L140-L150

And that's causing the namespace reader to be skipped.

**Comment by jaraco** [comment] 2024-08-20 16:14
> So, fixing the root issue might also address the secondary issue.

And indeed it does.

**Closed** 2024-09-09 17:00 UTC
Labels: bug

**Comment by USSX-Hares** [comment] 2025-07-01 14:57
Will this be ported to 3.12, or will it only be present in 3.13?
