### ISSUE TITLE
files(...).joinpath doesn't accept variable number of arguments in Python 3.10+

### ISSUE THREAD

**Issue by Jakub-CZ** [python/importlib_resources#257] opened 2022-07-12 15:30 UTC
This happens to me when I try to access resources in a native namespace package.

Tested on:
- Windows, `Python 3.10.4`
- Docker in WSL2, image `python:3.10-slim`, `Python 3.10.5`

---

The reason seems to be that `importlib_resources.files()` returns `MultiplexedPath` from stdlib (`importlib.readers`) rather than from `importlib_resources.readers`.

To recreate:
1. Install any namespace package, e.g. `sphinxcontrib-htmlhelp`;
   ```
   pip install sphinxcontrib-htmlhelp
   ```

1. Use `files` with `joinpath` to get the path of  a resource.
   ```python
   from importlib_resources import files

   print(root:=files('sphinxcontrib'), 'from', root.__module__)
   print(root.joinpath('htmlhelp', 'templates'))
   ```

Expected output (which I get with Pythons 3.7-3.9):
```
MultiplexedPath('/usr/local/lib/python3.9/site-packages/sphinxcontrib') from importlib_resources.readers
/usr/local/lib/python3.9/site-packages/sphinxcontrib/htmlhelp/templates
```

Bug with Pythons 3.10:
```
MultiplexedPath('/usr/local/lib/python3.10/site-packages/sphinxcontrib') from importlib.readers
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: MultiplexedPath.joinpath() takes 2 positional arguments but 3 were given
```

I also tested with the code in #254 but to no aval.

**Comment by jaraco** [comment] 2022-07-22 18:48
I see support for namespace packages was added in 8e1a218a0e released in `importlib_resources` 3.2.0 and Python 3.10. I'm able to replicate the error with this one-liner (requires [pip-run](https://pypi.org/project/pip-run)):

```
$ pip-run -q sphinxcontrib-htmlhelp importlib_resources -- -c "import importlib_resources as resources; resources.files('sphinxcontrib').join
path('htmlhelp', 'templates')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: MultiplexedPath.joinpath() takes 2 positional arguments but 3 were given
```

In that release, the [`MultiplexedPath.joinpath` only accepted one parameter](https://github.com/python/importlib_resources/blob/8e1a218a0e45ef28eee7e56c1040138f9615326c/importlib_resources/readers.py#L84).

But that restriction was lifted in 64403234fd (released in 5.8.0).

But somehow, it seems that the `MultiplexedPath` on Python 3.10 is being preferred even though `importlib_resources` 5.9 is being invoked.

**Comment by jaraco** [comment] 2022-07-22 19:12
I think I understand what's going on:

- `importlib_resources` [wraps the __spec__](https://github.com/python/importlib_resources/blob/31102947fd9babef636d3b82c2a5d58883f9c1f5/importlib_resources/_adapters.py#L165-L170) in order to supply a TraversableResources reader if the loader/spec doesn't already provide one.

- Because Python 3.10 provides one, however, importlib_resources [defers to that implementation](https://github.com/python/importlib_resources/blob/31102947fd9babef636d3b82c2a5d58883f9c1f5/importlib_resources/_adapters.py#L151-L156), so on Python 3.10 and 3.11, the users get an experience based on objects in the stdlib. With Python 3.12, users will get the importlib_resources 5.8+ experience.

It's not obvious to me how `importlib_resources` could intercept these calls for later versions of Python that were previously adequate, and even less obvious that's what _should_ happen. `importlib_resources` has to support loaders from a range of Python versions as well as a range of behaviors from custom loaders.

As a short-term workaround, I suggest to use `.joinpath('htmlhelp').joinpath('templates')`, which should work in all Python versions. It's possible that `.joinpath('htmlhelp/templates')` will also work, but that's also risky, because support for that was improved recently.

**Comment by jaraco** [comment] 2022-07-22 19:15
@FFY00 I'd like your opinion - do you think based on this report that `importlib_resources` should be more aggressive about supplying its own Readers and Path objects?

**Comment by FFY00** [comment] 2022-07-22 19:32
I think that would be something worth exploring. That behavior seems desirable, but like you mentioned, the implementation might be a bit tricky. If we can come up with a reasonable way of doing this, it would be nice to have it, otherwise, I wouldn't worry *too* much.

**Comment by Jakub-CZ** [comment] 2024-03-15 18:45
Here's a unit test that fails in Python 3.10 (and only in that one, AFAIK):

```diff
diff --git a/importlib_resources/tests/test_files.py b/importlib_resources/tests/test_files.py
index 9e45f70..3e86ec6 100644
--- a/importlib_resources/tests/test_files.py
+++ b/importlib_resources/tests/test_files.py
@@ -34,6 +34,11 @@ class FilesTests:
     def test_traversable(self):
         assert isinstance(resources.files(self.data), Traversable)

+    def test_joinpath_with_multiple_args(self):
+        files = resources.files(self.data)
+        binfile = files.joinpath('subdirectory', 'binary.file')
+        self.assertTrue(binfile.is_file())
+
     def test_old_parameter(self):
         """
         Files used to take a 'package' parameter. Make sure anyone
```

**Comment by jaraco** [comment] 2024-03-16 15:01
The issue is with this logic:

https://github.com/python/importlib_resources/blob/9f5b437d9af146edde9e4d1f2757cb808b5c3803/importlib_resources/future/adapters.py#L26-L28

On Python 3.10, the module name for the loaders is "importlib.readers", not "importlib.resources.readers".

Thanks so much for the test, which (shame on me) should have been included in the original solution.

**Closed** 2024-03-16 15:07 UTC
