### ISSUE TITLE
Suggestion: MultiplexedPath.joinpath() to return MultiplexedPaths for subdirs that exist in multiple base dirs

### ISSUE THREAD

**Issue by jooste** [python/importlib_resources#264] opened 2022-09-05 14:47 UTC
Hello all,

I posted this suggestion recently at discuss.python.org, but realised it's probably better suited here :)

I recently looked into MultiplexedPath as a way to provide easy access to data files that can be either part of a packages resources, or reside in a local user directory. In my case, the contents of both these base paths have the same directory structure. Currently, when accessing one of these subdirectories with `joinpath()` you only get a Path object pointing to the first occurrence of the requested subdirectory that was found.

My suggestion would be to in these cases instead return another MultiplexedPath object, so that when you iterate over the contents of one of these common subfolders you get the merged contents of all existing common subdirectories, in the same way that MultiplexedPath.iterdir() now also returns the combined results of all of its included base paths.

An example implementation, based on the  version of MultiplexedPath in python 3.10.3 importlib:
```python
    def joinpath(self, child):
        # first try to find child in current paths
        paths = []
        for path in (p / child for p in self._paths):
            if path.exists():
                if path.is_dir():
                    # If it's a dir, try to combine it with others
                    paths.append(path)
                else:
                    # If it's a file, immediately return it
                    return path

        # if it does not exist, construct it with the first path
        return MultiplexedPath(*paths) if len(paths) > 1 else \
            paths[0] if len(paths) == 1 else self._paths[0] / child
```
I realise that this implementation (and the python/importlib version it is based on) is different from the current structure in this repository, but it does show the intention of the modified functionality.

I'm interested to hear your opinion!

**Comment by jaraco** [comment] 2022-10-08 00:50
I'm going to close this in favor of #265, but if the issue isn't addressed there, we can revisit this one.

**Closed by jaraco** 2022-10-08 00:50 UTC
